project:
  type: website
  output-dir: docs

website:
  title: "Christina Wong"
  site-url: "christinanj-wong.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: work.qmd
        text: Work
      - href: about.qmd
        text: About
      - icon: linkedin
        href: https://www.linkedin.com/in/christinanjwong/
      - icon: github
        href: https://github.com/christinanj-wong
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

freeze: auto 
